"""Contains URLs and roles
"""
JIRA_BASE_URL = "https://10.50.4.37:8443/rest/api/2/"
VMT_BASE_URL = "http://127.0.0.1:5000"
CHECK_ROLE = f"{VMT_BASE_URL}/check-auth"
JIRA_URL = f"""{JIRA_BASE_URL}search?jql=project = "VBBT" AND status != Closed AND reporter = """
JIRA_ADMIN_URL = f"""{JIRA_BASE_URL}search?jql=project = "VBBT" AND status != Closed AND assignee = """
ADMIN_ROLE = "01"
USER_ROLE = "02"
PADDING = 16
ADMIN_CODE  = "25"
SENIOR_ADMIN_CODE = "26"
ALGORITHM = "HS256"
VM_BASE_URL = "https://10.50.4.15/rest"
SESSION_API_URL = f"{VM_BASE_URL}/com/vmware/cis/session"
FOLDER_API_URL = f"{VM_BASE_URL}/vcenter/folder"
DATASTORE_API_URL = f"{VM_BASE_URL}/vcenter/datastore"
CREATE_VM_API_URL = f"{VM_BASE_URL}/vcenter/vm"
DELETE_VM_API_URL = f"{VM_BASE_URL}/vcenter/vm/"
GET_VM_API_URL = f"{VM_BASE_URL}/vcenter/vm"
JIRA_CREATE_ISSUE_URL = f"""{JIRA_BASE_URL}issue"""
IN_PROGRESS_ID = "4"
TRIAGE_ID = "711"
CLOSE_ID = "2"
EPIC_ID = "VBT-1"